version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      
  pre_build:
    commands:
      - echo Checking for changes in nodejs-hello-world or python-hello-world...
      # Check if there are changes in the Node.js directory
      - |
        if git diff --name-only $CODEBUILD_SRC_DIR | grep -q "^nodejs"; then
          echo "Node.js directory has changes. Running Node.js build...";
          export RUN_NODEJS=true;
        fi
      # Check if there are changes in the Python directory
      - |
        if git diff --name-only $CODEBUILD_SRC_DIR | grep -q "^python"; then
          echo "Python directory has changes. Running Python build...";
          export RUN_PYTHON=true;
        fi

  build:
    commands:
      - echo Starting build...
      
      # If Node.js directory has changes, run the Node.js build steps
      - |
        if [ "$RUN_NODEJS" == "true" ]; then
          echo "Building Node.js app...";
          cd nodejs;
          docker build -t nodejs .;
        fi

      # If Python directory has changes, run the Python build steps
      - |
        if [ "$RUN_PYTHON" == "true" ]; then
          echo "Building Python app...";
          cd python;
          docker build -t python .;
        fi

  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - '**/*'
