version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      # Clone the repository to get the latest changes
      echo "Cloning the repository to check for the latest commits"
      git clone https://github.com/NavjitK/nodepy.git /tmp/repo
      cd /tmp/repo
      
      # Get the latest commit timestamp for the Node.js folder
      node_commit=$(git log -1 --format="%ct" nodejs)
      
      # Get the latest commit timestamp for the Python folder
      python_commit=$(git log -1 --format="%ct" python)

  build:
    commands:
      # Compare the commit times and decide which folder to build
      if [ $node_commit -gt $python_commit ]; then
        echo "Building Node.js application"
        # Build Docker image for Node.js
        cd /tmp/repo/nodejs
        docker build -t nodejs-app -f Dockerfile-nodejs .
      else
        echo "Building Python application"
        # Build Docker image for Python
        cd /tmp/repo/python
        docker build -t python-app -f Dockerfile-python .
      fi

  post_build:
    commands:
      echo "Build complete. The relevant Docker image has been built."
      # Optionally push the built image to a registry like ECR
      # aws ecr get-login-password --region your-region | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.<region>.amazonaws.com
      # docker tag nodejs-app <aws_account_id>.dkr.ecr.<region>.amazonaws.com/your-repository:latest
      # docker push <aws_account_id>.dkr.ecr.<region>.amazonaws.com/your-repository:latest
