version: 0.2

phases:
  install:
    commands:
      echo "Cloning the repository to check for the latest commits"
      git clone https://github.com/NavjitK/nodepy.git /tmp/repo
      cd /tmp/repo
      node_commit=$(git log -1 --format="%ct" nodejs)
      echo "Node.js latest commit timestamp: $node_commit"
      python_commit=$(git log -1 --format="%ct" python)
      echo "Python latest commit timestamp: $python_commit"

  build:
    commands:
      if [ $node_commit -gt $python_commit ]; then
        echo "Building Node.js application"
        cd /tmp/repo/nodejs && docker build -t nodejs-app -f Dockerfile-nodejs . 
      else
        echo "Building Python application"
        cd /tmp/repo/python && docker build -t python-app -f Dockerfile-python .
      fi

  post_build:
    commands:
      echo "Build complete. The relevant Docker image has been built."
      # Optionally push the built image to a registry like ECR
      # aws ecr get-login-password --region your-region | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.<region>.amazonaws.com
      # docker tag nodejs-app <aws_account_id>.dkr.ecr.<region>.amazonaws.com/your-repository:latest
      # docker push <aws_account_id>.dkr.ecr.<region>.amazonaws.com/your-repository:latest
