# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container
COPY . .

# Install any needed dependencies (if you had any, like in requirements.txt)
# RUN pip install --no-cache-dir -r requirements.txt

# Define the command to run your app
CMD [ "python", "hello.py" ]
